[package]
name = "rg_vulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
rg_common = { path="../rg_common" }
vulkanalia = { version="0.29.0", features = ["libloading", "provisional", "window"] }
winit = "0.30.12"
log = "0.4.21"
cgmath = "0.18.0"
thiserror = "2.0.17"
