[package]
name = "rg_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "rg_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "2.0.72"
quote = "1.0.39"
paste = "1.0.15"
proc-macro2 = "1.0.94"
toml = "0.9.2"
