[package]
name = "rg_common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
dirs = "5.0.1"
toml = "0.8.19"
serde = {  version = "1.0.204", features = ["derive"] }
rg_macros = { path = "../rg_macros" }
argh = "0.1.13"
snafu = "0.8.5"
