[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
log4rs = "1.3.0"
core = { path = "../core" }
math = { path = "../math" }
anyhow = "1.0.86"
serde = "1.0.203"
rmp-serde = "1.3.0"
mio = "1.0.0"