[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
log4rs = "1.3.0"
rg-common = { path = "../rg-common" }
math = { path = "../math" }
rg-macros = { path = "../rg-macros" }
anyhow = "1.0.86"
rsa = { version = "0.9.6", features = ["serde"] }
rand = "0.8.5"
serde = "1.0.204"
toml = "0.8.19"
bitcode = { version = "0.6.0", features = ["serde"] }