[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
log4rs = "1.3.0"
core = { path = "../core" }
math = { path = "../math" }
anyhow = "1.0.86"
serde = "1.0.203"
rmp-serde = "1.3.0"
mio = { version = "1.0.0", features = ["os-poll"] }
rsa = { version = "0.9.6", features = ["serde"] }
rand = "0.8.5"
chrono = "0.4.38"
toml = "0.8.14"