extern crate self as rg_common;

pub use arguments::Arguments;
pub use commands::CommandRegistry;
pub use files::Files;
pub use vars::FromStrMutator;
pub use vars::FromValue;
pub use vars::VarBag;
pub use vars::VarRegistry;
pub use vars::Variable;
pub use vars::VariableError;
pub use vars::VarRegistryError;
pub use vars::wrap_var_bag;
pub use plugin::Plugin;
pub use app::App;
pub use config::save_config;

mod arguments;
mod app;
mod cmd_parser;
pub mod commands;
mod config;
mod files;
mod pool;
mod v_from;
mod v_from_str;
mod v_from_value;
mod vars;
mod test;
mod plugin;
mod asset;
