debug = true

[server]
address = "127.0.0.1:0"
key_bits = 512
password = "123456"

[client]

[client.bindings]
Escape = "toggle_menu"
Backquote = "toggle_console"
KeyW = "forward"
KeyS = "backward"
KeyA = "strafe_left"
KeyD = "strafe_right"
Space = "jump"
KeyC = "crouch"
ShiftLeft = "sprint"
KeyE = "use"
ArrowLeft = "left"
ArrowRight = "right"
Mouse1 = "fire"